import React, { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls";
import { parseDockedLigandFromPDBQT, parsePDBtoCA, parsePDBLigand } from "./parse";

// ---- physics helpers (vector ops on plain objects) ----
const MIN_DIST = 1e-3;
const residueCharge = { ARG:1, LYS:1, ASP:-1, GLU:-1 };
function v3(x=0,y=0,z=0){ return {x,y,z}; }
function vadd(a,b){ return {x:a.x+b.x,y:a.y+b.y,z:a.z+b.z}; }
function vsub(a,b){ return {x:a.x-b.x,y:a.y-b.y,z:a.z-b.z}; }
function vmul(a,s){ return {x:a.x*s,y:a.y*s,z:a.z*s}; }
function vdot(a,b){ return a.x*b.x + a.y*b.y + a.z*b.z; }
function vlen(a){ return Math.sqrt(Math.max(0, vdot(a,a))); }
function vzero(a){ a.x=0;a.y=0;a.z=0; return a; }
function clampR(r){ return (r < MIN_DIST) ? MIN_DIST : r; }
function randn_bm(){ let u=0,v=0; while(u===0) u=Math.random(); while(v===0) v=Math.random(); return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v); }

// ---- Color palettes for secondary structure ----
// Each loop/helix/sheet segment gets a distinct color from these palettes
const LOOP_COLORS = [
  0xFF6B6B, 0xFFA94D, 0xFFD93D, 0x6BCB77, 0x4D96FF,
  0xC77DFF, 0xFF6AC1, 0x45B7D1, 0xFF8C42, 0xA8E6CE,
  0xDDA0DD, 0x98D8C8, 0xF7DC6F, 0xBB8FCE, 0x76D7C4,
  0xF1948A, 0x85C1E9, 0xF0B27A, 0xABEBC6, 0xD2B4DE,
];
const HELIX_COLORS = [
  0xFF4444, 0xFF6666, 0xCC3333, 0xE05555, 0xFF3333,
  0xDD4444, 0xEE5555, 0xBB2222, 0xFF5252, 0xE04040,
];
const SHEET_COLORS = [
  0x4488FF, 0x5599FF, 0x3377EE, 0x6699FF, 0x2266DD,
  0x4477EE, 0x5588EE, 0x3366CC, 0x77AAFF, 0x2255CC,
];

// Element colors for ligand atoms (CPK-like)
const ELEMENT_COLORS = {
  C: 0x909090, N: 0x3050F8, O: 0xFF0D0D, S: 0xFFFF30,
  P: 0xFF8000, H: 0xFFFFFF, FE: 0xE06633, CL: 0x1FF01F,
  BR: 0xA62929, F: 0x90E050, ZN: 0x7D80B0, MG: 0x8AFF00,
  CA: 0x3DFF00, NA: 0xAB5CF2, K: 0x8F40D4, MN: 0x9C7AC7,
  DEFAULT: 0xBFA6FE
};

function getElementColor(element) {
  const el = (element || 'C').toUpperCase();
  return ELEMENT_COLORS[el] || ELEMENT_COLORS.DEFAULT;
}

// Get color for a residue based on its secondary structure
function getSSColor(coord) {
  if (coord.ss === 'helix') {
    return HELIX_COLORS[(coord.helixIndex - 1) % HELIX_COLORS.length];
  }
  if (coord.ss === 'sheet') {
    return SHEET_COLORS[(coord.sheetIndex - 1) % SHEET_COLORS.length];
  }
  // loop - each segment gets a unique color
  return LOOP_COLORS[(coord.loopIndex - 1) % LOOP_COLORS.length];
}

// Preset protein/ligand pairs with PDB IDs
const PROTEIN_PRESETS = [
  { name: 'Hemoglobin + Heme', pdbId: '1A3N', desc: 'Oxygen-carrying protein with iron-porphyrin cofactor', hasLigand: true },
  { name: 'HIV Protease + Indinavir', pdbId: '1HSG', desc: 'Antiretroviral drug in homodimer active site', hasLigand: true },
  { name: 'Lysozyme + NAG', pdbId: '1LZA', desc: 'Enzyme with N-acetylglucosamine substrate', hasLigand: true },
  { name: 'Insulin', pdbId: '4INS', desc: 'Peptide hormone, 2-chain structure', hasLigand: false },
  { name: 'Trypsin + Benzamidine', pdbId: '3PTB', desc: 'Serine protease with competitive inhibitor', hasLigand: true },
  { name: 'Green Fluorescent Protein', pdbId: '1EMA', desc: 'Beta-barrel fluorescent protein from jellyfish', hasLigand: false },
  { name: 'Crambin (small)', pdbId: '1CRN', desc: 'Small 46-residue plant protein, great for testing', hasLigand: false },
  { name: 'Ubiquitin', pdbId: '1UBQ', desc: 'Small regulatory protein, alpha+beta fold', hasLigand: false },
];

// ---- AutoDock atom type mapping ----
function getAutodockType(element, atomName) {
  const el = (element || 'C').toUpperCase().replace(/[0-9]/g, '').trim();
  switch (el) {
    case 'C':  return 'C';
    case 'N':  return 'NA';
    case 'O':  return 'OA';
    case 'S':  return 'SA';
    case 'H':  return 'HD';
    case 'P':  return 'P';
    case 'F':  return 'F';
    case 'CL': return 'Cl';
    case 'BR': return 'Br';
    case 'I':  return 'I';
    case 'FE': return 'Fe';
    case 'ZN': return 'Zn';
    case 'MG': return 'Mg';
    case 'CA': return 'Ca';
    case 'MN': return 'Mn';
    case 'NA': return 'Na';
    case 'K':  return 'K';
    default:   return el.length <= 2 ? el : el.substring(0, 2);
  }
}

// Generate protein PDBQT from raw PDB text (all-atom ATOM records)
function generateProteinPDBQT(pdbText) {
  const lines = pdbText.split('\n');
  const out = [];
  out.push('REMARK  PDBQT receptor - generated by Protein Structure Viewer');
  let serial = 1;
  for (const line of lines) {
    const recType = line.substring(0, 6).trim();
    if (recType !== 'ATOM') continue;
    const resname = line.substring(17, 20).trim();
    if (!resname) continue;
    const atomName = line.substring(12, 16).trim();
    const altLoc   = line.substring(16, 17).trim();
    if (altLoc && altLoc !== 'A') continue; // skip alternate conformations
    const chain  = line.substring(21, 22) || 'A';
    const resSeq = line.substring(22, 26);
    const x = parseFloat(line.substring(30, 38));
    const y = parseFloat(line.substring(38, 46));
    const z = parseFloat(line.substring(46, 54));
    if (isNaN(x) || isNaN(y) || isNaN(z)) continue;
    const rawEl = line.substring(76, 78).trim();
    const element = rawEl || atomName.replace(/[0-9]/g, '').charAt(0);
    const adType = getAutodockType(element, atomName);
    const charge = '0.000';
    const sn   = serial.toString().padStart(5);
    const aStr = (' ' + atomName).padEnd(4).substring(0, 4);
    const xStr = x.toFixed(3).padStart(8);
    const yStr = y.toFixed(3).padStart(8);
    const zStr = z.toFixed(3).padStart(8);
    out.push(`ATOM  ${sn} ${aStr} ${resname.padEnd(3)} ${chain}${resSeq}    ${xStr}${yStr}${zStr}  1.00  0.00    ${charge.padStart(6)} ${adType}`);
    serial++;
  }
  out.push('END');
  return out.join('\n');
}

// Generate ligand PDBQT from parsed ligand atoms array
function generateLigandPDBQT(ligandAtoms) {
  if (!ligandAtoms || ligandAtoms.length === 0) return '';
  const out = [];
  out.push('REMARK  PDBQT ligand - generated by Protein Structure Viewer');
  out.push('ROOT');
  ligandAtoms.forEach((atom, i) => {
    const serial  = (i + 1).toString().padStart(5);
    const aName   = (atom.atomName || atom.element || 'C').padEnd(4).substring(0, 4);
    const resname = (atom.resname || 'LIG').padEnd(3).substring(0, 3);
    const chain   = (atom.chain || 'Z').charAt(0);
    const resSeq  = ((atom.resSeq || 1) + '').padStart(4);
    const xStr    = atom.x.toFixed(3).padStart(8);
    const yStr    = atom.y.toFixed(3).padStart(8);
    const zStr    = atom.z.toFixed(3).padStart(8);
    const element = (atom.element || 'C').toUpperCase();
    const adType  = getAutodockType(element, atom.atomName);
    const charge  = '0.000';
    out.push(`HETATM${serial}  ${aName}${resname} ${chain}${resSeq}    ${xStr}${yStr}${zStr}  1.00  0.00    ${charge.padStart(6)} ${adType}`);
  });
  out.push('ENDROOT');
  out.push('TORSDOF 0');
  return out.join('\n');
}

// ---- System component ----
export default function System(){
  const mountRef = useRef(null);
  const threeRef = useRef({});
  const rawPDBRef = useRef(null); // full raw PDB text for all-atom export
  const [dtVal, setDtVal] = useState(1.0);
  const [tempVal, setTempVal] = useState(300);
  const [epsVal, setEpsVal] = useState(1.0);
  const [gammaVal, setGammaVal] = useState(0.2);
  const [running, setRunning] = useState(false);
  const [stats, setStats] = useState({ step:0, K:0, U:0, E:0 });
  const [hoveredResidue, setHoveredResidue] = useState(null);
  const [structureInfo, setStructureInfo] = useState(null);
  const [loadingPDB, setLoadingPDB] = useState(false);
  const [colorMode, setColorMode] = useState('structure'); // 'structure' or 'charge'
  const [ligandInfo, setLigandInfo] = useState(null); // { name, atomCount, elements }
  const [showLigand, setShowLigand] = useState(true);
  const [selectedPreset, setSelectedPreset] = useState(null);
  const [metalness, setMetalness] = useState(0.3);
  const [roughness, setRoughness] = useState(0.5);
  const [emissiveIntensity, setEmissiveIntensity] = useState(0);
  const [lightIntensity, setLightIntensity] = useState(0.8);
  const [proteinPDBQT, setProteinPDBQT] = useState(null);
  const [ligandPDBQT, setLigandPDBQT] = useState(null);
  const [pdbqtStatus, setPdbqtStatus] = useState(null); // null | 'generating' | 'ready'
  const [hasFullAtom, setHasFullAtom] = useState(false);
  const [viewMode, setViewMode] = useState('both'); // 'both'|'split'|'protein'|'ligand'
  const [boundResiduesDistance, setBoundResiduesDistance] = useState(4.5); // distance threshold in Angstroms
  const [boundResidues, setBoundResidues] = useState([]); // indices of residues within distance of ligand
  const [showBoundResidues, setShowBoundResidues] = useState(false); // toggle highlighting
  const [boundResidueInfo, setBoundResidueInfo] = useState([]); // store residue info for display
  const [vinaScore, setVinaScore] = useState(null); // Vina binding affinity + RMSD
  const [vinaScoring, setVinaScoring] = useState(false); // Vina scoring in progress
  const [vinaResultText, setVinaResultText] = useState(null); // Raw Vina PDBQT result text

  useEffect(() => {
    const container = mountRef.current;
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(45, container.clientWidth/container.clientHeight, 0.1, 2000);
    camera.position.set(0, 20, 40);

    const renderer = new THREE.WebGLRenderer({ antialias:true });
    renderer.setSize(container.clientWidth, container.clientHeight);
    renderer.setClearColor(0x071025, 1);
    container.appendChild(renderer.domElement);

    const controls = new OrbitControls(camera, renderer.domElement);
    controls.target.set(0,0,0); controls.update();

    scene.add(new THREE.AmbientLight(0x5a6f8a, 0.6));
    const l1 = new THREE.DirectionalLight(0xffffff, 0.8); l1.position.set(10,20,10); scene.add(l1);

    // groups
    const beadGroup = new THREE.Group(); scene.add(beadGroup);
    const bondGroup = new THREE.Group(); scene.add(bondGroup);
    const nbGroup = new THREE.Group(); scene.add(nbGroup);
    const traceGroup = new THREE.Group(); scene.add(traceGroup);
    const ligandGroup = new THREE.Group(); scene.add(ligandGroup);
    const labelGroup = new THREE.Group(); scene.add(labelGroup);

    // raycaster for dragging & hover
    const ray = new THREE.Raycaster();
    const pointer = new THREE.Vector2();
    let dragging = null;
    let mouseDown = false;

    // simulation state
    let particles = [];
    let bonds = [];
    let stepCount = 0;
    let coordsData = []; // raw parsed coordinates with SS info
    let ligandAtomsData = []; // raw ligand atoms for export

    const params = {
      dt: dtVal, temp: tempVal, eps: epsVal, sigma:1.0,
      kbond:100, r0:1.5, gamma: gammaVal, cutoff:6.0
    };

    threeRef.current = { scene, camera, renderer, controls, particles, bonds, params, beadGroup, bondGroup, nbGroup, traceGroup, ligandGroup, setRunning };

    // ---- color mode accessor ----
    let currentColorMode = 'structure';

    // ---- protein lighting state ----
    let currentMetalness = 0.3;
    let currentRoughness = 0.5;
    let currentEmissiveIntensity = 0;

    // ---------- create meshes ----------
    function createMeshes(){
      beadGroup.clear(); bondGroup.clear(); nbGroup.clear(); traceGroup.clear(); ligandGroup.clear(); labelGroup.clear();
      const beadGeom = new THREE.SphereGeometry(0.6, 16, 12);

      for(let i=0;i<particles.length;i++){
        const p = particles[i];
        const coord = coordsData[i] || {};
        let color;
        
        // Check if this residue is bound to ligand
        const isBound = showBoundResidues && boundResidues.includes(i);
        
        if (isBound) {
          // Highlight bound residues with yellow/gold
          color = 0xFFD700; // Gold
        } else if (currentColorMode === 'structure' && coord.ss) {
          color = getSSColor(coord);
        } else {
          color = (p.charge>0) ? 0xffb3b3 : (p.charge<0 ? 0xb3d9ff : 0xdadada);
        }
        const mat = new THREE.MeshStandardMaterial({
          color, metalness: currentMetalness, roughness: currentRoughness,
          emissive: currentEmissiveIntensity > 0 ? color : 0x000000,
          emissiveIntensity: currentEmissiveIntensity
        });
        const mesh = new THREE.Mesh(beadGeom, mat);
        mesh.position.set(p.pos.x, p.pos.y, p.pos.z);
        mesh.userData.index = i;
        mesh.userData.resname = coord.resname || 'UNK';
        mesh.userData.resSeq = coord.resSeq;
        mesh.userData.chain = coord.chain;
        mesh.userData.ss = coord.ss || 'loop';
        mesh.userData.loopIndex = coord.loopIndex || 0;
        mesh.userData.isBound = isBound;
        beadGroup.add(mesh);
        p.mesh = mesh;
      }
      // bonds (cylinders) - color matches the two residues
      const cylGeom = new THREE.CylinderGeometry(0.12,0.12,1,8);
      for(let b of bonds){
        const coordA = coordsData[b[0]] || {};
        const coordB = coordsData[b[1]] || {};
        
        // If either end is bound, color the bond as bound
        const aBound = showBoundResidues && boundResidues.includes(b[0]);
        const bBound = showBoundResidues && boundResidues.includes(b[1]);
        
        let bondColor = 0x7f9bb3;
        if (aBound || bBound) {
          bondColor = 0xFFD700; // Gold for bound
        } else if (currentColorMode === 'structure' && coordA.ss && coordB.ss) {
          // use color of lower-index residue for the bond
          bondColor = getSSColor(coordA);
        }
        const cylMat = new THREE.MeshStandardMaterial({
          color: bondColor, metalness: currentMetalness, roughness: currentRoughness,
          emissive: currentEmissiveIntensity > 0 ? bondColor : 0x000000,
          emissiveIntensity: currentEmissiveIntensity
        });
        const mesh = new THREE.Mesh(cylGeom, cylMat);
        bondGroup.add(mesh);
      }
      updateTrace();
    }

    function updateTrace(){
      traceGroup.clear();
      if(particles.length<2) return;

      // Draw trace segments colored by secondary structure
      if (currentColorMode === 'structure' && coordsData.length > 0) {
        for (let i = 0; i < particles.length - 1; i++) {
          const a = particles[i], b = particles[i+1];
          const pts = [
            new THREE.Vector3(a.pos.x, a.pos.y, a.pos.z),
            new THREE.Vector3(b.pos.x, b.pos.y, b.pos.z)
          ];
          
          // Check if this segment's residues are bound
          const aBound = showBoundResidues && boundResidues.includes(i);
          const bBound = showBoundResidues && boundResidues.includes(i+1);
          
          const coordA = coordsData[i] || {};
          let color = getSSColor(coordA);
          if (aBound || bBound) {
            color = 0xFFD700; // Gold for bound segments
          }
          
          const geom = new THREE.BufferGeometry().setFromPoints(pts);
          const mat = new THREE.LineBasicMaterial({ color, linewidth: 2 });
          const line = new THREE.Line(geom, mat);
          traceGroup.add(line);
        }
      } else {
        const pts = particles.map(p => new THREE.Vector3(p.pos.x, p.pos.y, p.pos.z));
        const geom = new THREE.BufferGeometry().setFromPoints(pts);
        const mat = new THREE.LineDashedMaterial({ color:0xa8c8ff, dashSize:0.2, gapSize:0.1 });
        const line = new THREE.Line(geom, mat);
        line.computeLineDistances();
        traceGroup.add(line);
      }
    }

    // Create tube/ribbon for secondary structure visualization
    function createStructureRibbons() {
      if (coordsData.length < 2 || currentColorMode !== 'structure') return;

      // Build thick tubes for helices, flat for sheets, thin for loops
      let segStart = 0;
      while (segStart < coordsData.length) {
        const ss = coordsData[segStart].ss;
        let segEnd = segStart;
        while (segEnd < coordsData.length - 1 && coordsData[segEnd + 1].ss === ss) {
          segEnd++;
        }

        if (segEnd > segStart) {
          const segPoints = [];
          for (let k = segStart; k <= segEnd; k++) {
            segPoints.push(new THREE.Vector3(particles[k].pos.x, particles[k].pos.y, particles[k].pos.z));
          }

          if (segPoints.length >= 2) {
            const curve = new THREE.CatmullRomCurve3(segPoints);
            let tubeRadius = 0.15; // loop
            let tubeSegments = segPoints.length * 4;

            if (ss === 'helix') tubeRadius = 0.35;
            else if (ss === 'sheet') tubeRadius = 0.25;

            const tubeGeom = new THREE.TubeGeometry(curve, tubeSegments, tubeRadius, 8, false);
            const color = getSSColor(coordsData[segStart]);
            const tubeMat = new THREE.MeshStandardMaterial({
              color,
              metalness: currentMetalness,
              roughness: currentRoughness,
              emissive: currentEmissiveIntensity > 0 ? color : 0x000000,
              emissiveIntensity: currentEmissiveIntensity,
              transparent: true,
              opacity: 0.6
            });
            const tubeMesh = new THREE.Mesh(tubeGeom, tubeMat);
            traceGroup.add(tubeMesh);
          }
        }
        segStart = segEnd + 1;
      }
    }

    function syncMeshes(){
      for(let i=0;i<particles.length;i++){
        const p = particles[i];
        if(p.mesh) p.mesh.position.set(p.pos.x, p.pos.y, p.pos.z);
      }
      let bi = 0;
      for(let b of bonds){
        const i = b[0], j = b[1];
        const mesh = bondGroup.children[bi++];
        if (!mesh) continue;
        const a = particles[i].pos, bb = particles[j].pos;
        const va = new THREE.Vector3(a.x,a.y,a.z), vb = new THREE.Vector3(bb.x,bb.y,bb.z);
        const mid = new THREE.Vector3().addVectors(va, vb).multiplyScalar(0.5);
        const diff = new THREE.Vector3().subVectors(vb, va);
        const len = diff.length();
        mesh.position.copy(mid);
        const axis = new THREE.Vector3(0,1,0);
        const dir = diff.clone().normalize();
        mesh.quaternion.setFromUnitVectors(axis, dir);
        mesh.scale.set(1, len, 1);
      }

      nbGroup.clear();
      const showNon = document.getElementById('show-nonbond')?.checked;
      if(showNon){
        const mat = new THREE.LineBasicMaterial({ color:0xffffff, opacity:0.08, transparent:true });
        for(let i=0;i<particles.length;i++){
          for(let j=i+2;j<particles.length;j++){
            const a=particles[i].pos, b=particles[j].pos;
            const d = vlen(vsub(a,b));
            if(d < params.cutoff*1.0){
              const geom = new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(a.x,a.y,a.z), new THREE.Vector3(b.x,b.y,b.z)]);
              const line = new THREE.Line(geom, mat);
              nbGroup.add(line);
            }
          }
        }
      }
      updateTrace();
      createStructureRibbons();
    }

    // ---------- force computation ----------
    function computeForces(){
      for(let p of particles) vzero(p.force);
      const k = params.kbond, r0 = params.r0;
      for(let b of bonds){
        const i = b[0], j = b[1];
        const pi = particles[i], pj = particles[j];
        const rij = vsub(pj.pos, pi.pos);
        let dist = vlen(rij) || MIN_DIST;
        const dr = dist - r0;
        const fm = -k * dr / dist;
        const f = vmul(rij, fm);
        pi.force = vadd(pi.force, f);
        pj.force = vsub(pj.force, f);
      }
      const cutoff2 = params.cutoff * params.cutoff;
      const sigma = params.sigma;
      const eps = params.eps;
      const kq = 5.0;
      for(let i=0;i<particles.length;i++){
        for(let j=i+2;j<particles.length;j++){
          const pi = particles[i], pj = particles[j];
          const rij = vsub(pj.pos, pi.pos);
          const r2 = vdot(rij, rij);
          if(r2 > cutoff2) continue;
          let r = Math.sqrt(r2) || MIN_DIST;
          r = clampR(r);
          const sr6 = Math.pow(sigma/r, 6);
          const sr12 = sr6 * sr6;
          const forceScalar = 24 * eps * (2*sr12 - sr6) / (r * r);
          const fLJ = vmul(rij, forceScalar);
          const q1 = pi.charge, q2 = pj.charge;
          let fC = {x:0,y:0,z:0};
          if(q1 !== 0 && q2 !== 0){
            const fCscalar = kq * (q1 * q2) / (r * r * r);
            fC = vmul(rij, fCscalar);
          }
          const total = vadd(fLJ, fC);
          pi.force = vadd(pi.force, total);
          pj.force = vsub(pj.force, total);
        }
      }
    }

    // ---------- integrator ----------
    function integrate(dt){
      for(let p of particles){
        const ax = p.force.x / p.mass, ay = p.force.y / p.mass, az = p.force.z / p.mass;
        p.vel.x += 0.5 * ax * dt;
        p.vel.y += 0.5 * ay * dt;
        p.vel.z += 0.5 * az * dt;
        p.pos.x += p.vel.x * dt;
        p.pos.y += p.vel.y * dt;
        p.pos.z += p.vel.z * dt;
      }
      computeForces();
      for(let p of particles){
        const ax = p.force.x / p.mass, ay = p.force.y / p.mass, az = p.force.z / p.mass;
        p.vel.x += 0.5 * ax * dt;
        p.vel.y += 0.5 * ay * dt;
        p.vel.z += 0.5 * az * dt;
        const gamma = params.gamma;
        if(gamma > 0){
          const kB = 1.0, T = params.temp;
          const c = Math.exp(-gamma * dt);
          const sigmaV = Math.sqrt((1 - c*c) * (kB * T / p.mass));
          p.vel.x = p.vel.x * c + sigmaV * randn_bm();
          p.vel.y = p.vel.y * c + sigmaV * randn_bm();
          p.vel.z = p.vel.z * c + sigmaV * randn_bm();
        }
      }
    }

    // ---------- energies ----------
    function computeEnergies(){
      let K=0, U=0;
      for(let p of particles){
        const v2 = vdot(p.vel, p.vel);
        K += 0.5 * p.mass * v2;
      }
      for(let b of bonds){
        const i=b[0], j=b[1];
        const r = vlen(vsub(particles[i].pos, particles[j].pos)) || MIN_DIST;
        const dr = r - params.r0;
        U += 0.5 * params.kbond * dr * dr;
      }
      const cutoff2 = params.cutoff * params.cutoff;
      for(let i=0;i<particles.length;i++){
        for(let j=i+2;j<particles.length;j++){
          const pi = particles[i], pj = particles[j];
          const r = vlen(vsub(pi.pos, pj.pos)) || MIN_DIST;
          if(r*r > cutoff2) continue;
          const sr6 = Math.pow(params.sigma / r, 6);
          U += 4 * params.eps * (sr6 * sr6 - sr6);
          const q1=pi.charge, q2=pj.charge;
          if(q1 !== 0 && q2 !== 0) U += 5.0 * (q1*q2) / r;
        }
      }
      return {K,U, E: K+U};
    }

    // ---------- simulation step ----------
    function simStep(){
      if(particles.length === 0) return;
      const dt = params.dt;
      const sub = Math.max(1, Math.round(dt / 0.5));
      const dts = dt / sub;
      for(let s=0;s<sub;s++){
        computeForces();
        integrate(dts);
      }
      stepCount++;
      
      // Recompute bound residues every 10 steps during simulation
      if (showBoundResidues && stepCount % 10 === 0 && ligandAtomsData.length > 0) {
        computeBoundResidues(boundResiduesDistance);
      }
      
      syncMeshes();
      const en = computeEnergies();
      setStats({ step: stepCount, K: en.K, U: en.U, E: en.E });
    }

    // animate
    let animId = null;
    function animate(){
      if(threeRef.current.isRunning) {
        simStep();
      }
      controls.update();
      renderer.render(scene, camera);
      animId = requestAnimationFrame(animate);
    }
    threeRef.current.isRunning = false;
    animId = requestAnimationFrame(animate);

    // ---------- system control helpers ----------
    function clearSystem(){
      particles = []; bonds = []; coordsData = []; ligandAtomsData = [];
      beadGroup.clear(); bondGroup.clear(); nbGroup.clear(); traceGroup.clear(); ligandGroup.clear(); labelGroup.clear();
      // Reset group offsets so split/separate view doesn't persist to new structure
      [beadGroup, bondGroup, nbGroup, traceGroup, ligandGroup].forEach(g => g.position.set(0,0,0));
      stepCount = 0;
      setStats({ step:0, K:0, U:0, E:0 });
      setStructureInfo(null);
      setLigandInfo(null);
      setBoundResidues([]);
      setBoundResidueInfo([]);
    }

    function buildFromCoords(coords){
      clearSystem();
      coordsData = coords;
      for(let i=0;i<coords.length;i++){
        const c = coords[i];
        const p = {
          pos: { x:c.x, y:c.y, z:c.z },
          vel: { x:(Math.random()-0.5)*0.2, y:(Math.random()-0.5)*0.2, z:(Math.random()-0.5)*0.2 },
          force: { x:0, y:0, z:0 },
          mass: 1.0,
          charge: residueCharge[c.resname] || 0,
          resname: c.resname || 'UNK'
        };
        particles.push(p);
      }
      for(let i=0;i<particles.length-1;i++) bonds.push([i,i+1]);
      createMeshes();
      centerView();

      // Build structure info summary
      const info = buildStructureInfo(coords);
      setStructureInfo(info);
    }

    function buildStructureInfo(coords) {
      const helices = new Set();
      const sheets = new Set();
      const loops = new Set();
      const chains = new Set();
      const residues = new Set();

      for (const c of coords) {
        chains.add(c.chain);
        residues.add(c.resname);
        if (c.ss === 'helix' && c.helixIndex > 0) helices.add(c.helixIndex);
        if (c.ss === 'sheet' && c.sheetIndex > 0) sheets.add(c.sheetIndex);
        if (c.ss === 'loop' && c.loopIndex > 0) loops.add(c.loopIndex);
      }

      // Build segment list for legend
      const segments = [];
      let segStart = 0;
      while (segStart < coords.length) {
        const ss = coords[segStart].ss || 'loop';
        let segEnd = segStart;
        while (segEnd < coords.length - 1 && (coords[segEnd + 1].ss || 'loop') === ss) {
          segEnd++;
        }
        const color = getSSColor(coords[segStart]);
        const label = ss === 'helix' ? `Helix ${coords[segStart].helixIndex}`
                    : ss === 'sheet' ? `Sheet ${coords[segStart].sheetIndex}`
                    : `Loop ${coords[segStart].loopIndex}`;
        segments.push({
          type: ss,
          label,
          color: '#' + color.toString(16).padStart(6, '0'),
          startRes: coords[segStart].resSeq,
          endRes: coords[segEnd].resSeq,
          count: segEnd - segStart + 1
        });
        segStart = segEnd + 1;
      }

      return {
        totalResidues: coords.length,
        chains: [...chains],
        uniqueResidues: [...residues],
        helixCount: helices.size,
        sheetCount: sheets.size,
        loopCount: loops.size,
        segments
      };
    }

    // Add ligand atoms to the scene
    function buildLigand(ligandAtoms) {
      ligandGroup.clear();
      if (!ligandAtoms || ligandAtoms.length === 0) {
        ligandAtomsData = [];
        setLigandInfo(null);
        return;
      }

      ligandAtomsData = ligandAtoms;

      // Collect ligand info for UI
      const resnames = [...new Set(ligandAtoms.map(a => a.resname))];
      const elements = [...new Set(ligandAtoms.map(a => (a.element || 'C').toUpperCase()))];
      setLigandInfo({
        name: resnames.join(', '),
        atomCount: ligandAtoms.length,
        elements: elements
      });

      // --- Atom spheres: larger CPK-style, bright emissive glow ---
      const sphereGeom = new THREE.SphereGeometry(0.8, 20, 16);
      const glowGeom   = new THREE.SphereGeometry(1.05, 14, 12);

      for (const atom of ligandAtoms) {
        const color = getElementColor(atom.element);

        const mat = new THREE.MeshStandardMaterial({
          color,
          metalness: 0.1,
          roughness: 0.25,
          emissive: color,
          emissiveIntensity: 0.65
        });
        const mesh = new THREE.Mesh(sphereGeom, mat);
        mesh.position.set(atom.x, atom.y, atom.z);
        ligandGroup.add(mesh);

        // Outer glow halo
        const glowMat = new THREE.MeshBasicMaterial({
          color,
          transparent: true,
          opacity: 0.28,
          depthWrite: false,
          side: THREE.BackSide
        });
        const glowMesh = new THREE.Mesh(glowGeom, glowMat);
        glowMesh.position.set(atom.x, atom.y, atom.z);
        ligandGroup.add(glowMesh);
      }

      // --- Bonds: thicker cylinders, wider threshold for C-S / C-Cl / C-N etc. ---
      const bondGeom = new THREE.CylinderGeometry(0.18, 0.18, 1, 10);
      for (let i = 0; i < ligandAtoms.length; i++) {
        for (let j = i + 1; j < ligandAtoms.length; j++) {
          const dx = ligandAtoms[i].x - ligandAtoms[j].x;
          const dy = ligandAtoms[i].y - ligandAtoms[j].y;
          const dz = ligandAtoms[i].z - ligandAtoms[j].z;
          const dist = Math.sqrt(dx*dx + dy*dy + dz*dz);
          if (dist < 2.1) {  // wider threshold catches C-S, C-Cl, C-N, C-O bonds
            const colorA = getElementColor(ligandAtoms[i].element);
            const colorB = getElementColor(ligandAtoms[j].element);
            const va  = new THREE.Vector3(ligandAtoms[i].x, ligandAtoms[i].y, ligandAtoms[i].z);
            const vb  = new THREE.Vector3(ligandAtoms[j].x, ligandAtoms[j].y, ligandAtoms[j].z);
            const mid = new THREE.Vector3().addVectors(va, vb).multiplyScalar(0.5);
            const diff = new THREE.Vector3().subVectors(vb, va);
            const len  = diff.length();
            const quat = new THREE.Quaternion().setFromUnitVectors(
              new THREE.Vector3(0,1,0), diff.clone().normalize()
            );

            const mkHalf = (color, fromPt, toPt) => {
              const m = new THREE.MeshStandardMaterial({
                color, metalness: 0.05, roughness: 0.3,
                emissive: color, emissiveIntensity: 0.45
              });
              const h = new THREE.Mesh(bondGeom, m);
              const center = new THREE.Vector3().addVectors(fromPt, toPt).multiplyScalar(0.5);
              h.position.copy(center);
              h.quaternion.copy(quat);
              h.scale.set(1, len * 0.5, 1);
              return h;
            };

            ligandGroup.add(mkHalf(colorA, va, mid));
            ligandGroup.add(mkHalf(colorB, mid, vb));
          }
        }
      }

      // --- 3D bounding wireframe sphere (visible from all angles) ---
      if (ligandAtoms.length > 1) {
        const center = new THREE.Vector3();
        ligandAtoms.forEach(a => center.add(new THREE.Vector3(a.x, a.y, a.z)));
        center.divideScalar(ligandAtoms.length);

        let maxR = 0;
        ligandAtoms.forEach(a => {
          const d = center.distanceTo(new THREE.Vector3(a.x, a.y, a.z));
          if (d > maxR) maxR = d;
        });
        const boundR = maxR + 1.5;

        // Wireframe sphere cage
        const cageGeom = new THREE.IcosahedronGeometry(boundR, 1);
        const cageMat  = new THREE.MeshBasicMaterial({
          color: 0x00ff99,
          wireframe: true,
          transparent: true,
          opacity: 0.25
        });
        const cage = new THREE.Mesh(cageGeom, cageMat);
        cage.position.copy(center);
        ligandGroup.add(cage);

        // Solid ghost surface inside the cage
        const surfGeom = new THREE.SphereGeometry(boundR, 24, 18);
        const surfMat  = new THREE.MeshBasicMaterial({
          color: 0x00ff88,
          transparent: true,
          opacity: 0.06,
          depthWrite: false,
          side: THREE.FrontSide
        });
        const surf = new THREE.Mesh(surfGeom, surfMat);
        surf.position.copy(center);
        ligandGroup.add(surf);
      }

      ligandGroup.visible = true;
    }

    // Export current structure as PyMOL .pml script
    function exportPyMOL() {
      if (coordsData.length === 0) {
        alert('No structure loaded to export');
        return;
      }

      // Build PDB content — use full-atom raw PDB when available, else CA-only fallback
      let pdbContent;
      const rawText = rawPDBRef.current;
      if (rawText) {
        // Keep ATOM, HETATM, CONECT records; drop waters
        const kept = rawText.split('\n').filter(line => {
          const rt = line.substring(0, 6).trim();
          if (rt !== 'ATOM' && rt !== 'HETATM' && rt !== 'CONECT') return false;
          const resname = line.substring(17, 20).trim();
          if (['HOH', 'WAT', 'DOD'].includes(resname)) return false;
          return true;
        });
        pdbContent = 'REMARK  Full-atom structure exported by Protein Structure Viewer\n'
          + kept.join('\n') + '\nEND\n';
      } else {
        // CA-only fallback
        const pdbLines = [];
        pdbLines.push('REMARK  Backbone (CA) export by Protein Structure Viewer');
        for (let i = 0; i < particles.length; i++) {
          const p = particles[i];
          const c = coordsData[i] || {};
          const serial  = (i + 1).toString().padStart(5);
          const resname = (c.resname || 'UNK').padStart(3);
          const chain   = (c.chain || 'A').charAt(0);
          const resSeq  = ((c.resSeq || i + 1) + '').padStart(4);
          const x = p.pos.x.toFixed(3).padStart(8);
          const y = p.pos.y.toFixed(3).padStart(8);
          const z = p.pos.z.toFixed(3).padStart(8);
          pdbLines.push(`ATOM  ${serial}  CA  ${resname} ${chain}${resSeq}    ${x}${y}${z}  1.00  0.00           C`);
        }
        const ligOffset = particles.length;
        for (let i = 0; i < ligandAtomsData.length; i++) {
          const a = ligandAtomsData[i];
          const serial  = (ligOffset + i + 1).toString().padStart(5);
          const aName   = (a.atomName || a.element || 'X').padEnd(4).substring(0, 4);
          const resname = (a.resname || 'LIG').padStart(3);
          const chain   = (a.chain || 'Z').charAt(0);
          const resSeq  = ((a.resSeq || 1) + '').padStart(4);
          const x = a.x.toFixed(3).padStart(8);
          const y = a.y.toFixed(3).padStart(8);
          const z = a.z.toFixed(3).padStart(8);
          const el = (a.element || 'C').padStart(2);
          pdbLines.push(`HETATM${serial}  ${aName}${resname} ${chain}${resSeq}    ${x}${y}${z}  1.00  0.00          ${el}`);
        }
        pdbLines.push('END');
        pdbContent = pdbLines.join('\n');
      }

      // Build PyMOL script
      const pmlLines = [];
      pmlLines.push('# PyMOL script generated by Protein Structure Viewer');
      pmlLines.push('# Open this file in PyMOL: File > Run Script');
      pmlLines.push('');
      pmlLines.push('from pymol import cmd');
      pmlLines.push('import tempfile, os');
      pmlLines.push('');
      pmlLines.push('pdb_data = """\\');
      for (const line of pdbContent.split('\n')) {
        pmlLines.push(line + '\\');
      }
      pmlLines.push('"""');
      pmlLines.push('');
      pmlLines.push('tmpfile = tempfile.NamedTemporaryFile(suffix=".pdb", delete=False, mode="w")');
      pmlLines.push('tmpfile.write(pdb_data)');
      pmlLines.push('tmpfile.close()');
      pmlLines.push('cmd.load(tmpfile.name, "structure")');
      pmlLines.push('os.unlink(tmpfile.name)');
      pmlLines.push('');

      pmlLines.push('# ---- Visualization Settings ----');
      pmlLines.push('cmd.bg_color("black")');
      pmlLines.push('');

      if (rawText) {
        // Full-atom: cartoon for protein, sticks+spheres for ligand
        pmlLines.push('# Protein: cartoon + surface');
        pmlLines.push('cmd.select("protein_sel", "polymer.protein")');
        pmlLines.push('cmd.hide("everything", "protein_sel")');
        pmlLines.push('cmd.show("cartoon", "protein_sel")');
        pmlLines.push('cmd.color("red", "protein_sel and ss h")');
        pmlLines.push('cmd.color("blue", "protein_sel and ss s")');
        pmlLines.push('cmd.color("white", "protein_sel and ss l+\'\'")');
        pmlLines.push('');
      } else {
        // CA-only fallback
        pmlLines.push('# Protein backbone (CA only)');
        pmlLines.push('cmd.select("protein_sel", "name CA")');
        pmlLines.push('cmd.show("spheres", "protein_sel")');
        pmlLines.push('cmd.set("sphere_scale", 0.4, "protein_sel")');
        pmlLines.push('cmd.show("sticks", "protein_sel")');
        pmlLines.push('cmd.color("red", "ss h")');
        pmlLines.push('cmd.color("blue", "ss s")');
        pmlLines.push('cmd.color("orange", "ss l+\'\'")');
        pmlLines.push('');
      }

      // Ligand visualization
      if (ligandAtomsData.length > 0 || rawText) {
        pmlLines.push('# Ligand: sticks + spheres + surface highlight');
        pmlLines.push('cmd.select("ligand_sel", "hetatm and not resn HOH+WAT+DOD")');
        pmlLines.push('cmd.hide("everything", "ligand_sel")');
        pmlLines.push('cmd.show("sticks", "ligand_sel")');
        pmlLines.push('cmd.show("spheres", "ligand_sel")');
        pmlLines.push('cmd.set("sphere_scale", 0.25, "ligand_sel")');
        pmlLines.push('cmd.set("stick_radius", 0.18, "ligand_sel")');
        pmlLines.push('cmd.util.cbag("ligand_sel")');
        pmlLines.push('');
        pmlLines.push('# Protein residues within 5 Å of ligand');
        pmlLines.push('cmd.select("binding_site", "polymer.protein within 5 of ligand_sel")');
        pmlLines.push('cmd.show("sticks", "binding_site")');
        pmlLines.push('cmd.set("stick_radius", 0.12, "binding_site")');
        pmlLines.push('');
      }

      pmlLines.push('# Final view');
      pmlLines.push('cmd.deselect()');
      pmlLines.push('cmd.zoom("all")');
      pmlLines.push('cmd.set("ray_shadows", 1)');
      pmlLines.push('cmd.set("antialias", 2)');
      pmlLines.push('cmd.set("ambient", 0.3)');
      pmlLines.push('cmd.set("spec_reflect", 0.5)');
      pmlLines.push('');
      const isFullAtom = !!rawText;
      pmlLines.push(`# Structure: ${coordsData.length} residues — ${isFullAtom ? 'full-atom' : 'CA backbone only'}`);
      if (ligandAtomsData.length > 0) {
        pmlLines.push(`# Ligand: ${ligandAtomsData.length} atoms`);
      }

      const pmlContent = pmlLines.join('\n');

      const blob = new Blob([pmlContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'structure.pml';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }

    function generateRandomChain(n){
      const coords = [];
      // Assign random secondary structure segments for demo
      let currentSS = 'loop';
      let loopIdx = 1, helixIdx = 0, sheetIdx = 0;
      let segLen = 0;
      const maxSegLen = () => currentSS === 'helix' ? 12 : currentSS === 'sheet' ? 6 : 5;

      for(let i=0;i<n;i++){
        segLen++;
        if (segLen > maxSegLen() || i === 0) {
          const r = Math.random();
          if (r < 0.35) { currentSS = 'helix'; helixIdx++; }
          else if (r < 0.55) { currentSS = 'sheet'; sheetIdx++; }
          else { currentSS = 'loop'; loopIdx++; }
          segLen = 1;
        }
        coords.push({
          x: i*params.r0*1.05 + (Math.random()-0.5)*0.2,
          y: (Math.random()-0.5)*0.2,
          z: (Math.random()-0.5)*0.2,
          resname: randomResidue(),
          chain: 'A',
          resSeq: i+1,
          ss: currentSS,
          loopIndex: currentSS === 'loop' ? loopIdx : -1,
          helixIndex: currentSS === 'helix' ? helixIdx : -1,
          sheetIndex: currentSS === 'sheet' ? sheetIdx : -1
        });
      }
      buildFromCoords(coords);
    }
    function randomResidue(){
      const keys = Object.keys(residueCharge);
      const others = ['ALA','GLY','SER','PHE','TYR','TRP','ASN'];
      const pool = keys.concat(others);
      return pool[Math.floor(Math.random()*pool.length)];
    }

    function centerView(){
      if(particles.length===0) return;
      let cx=0, cy=0, cz=0;
      for(let p of particles){ cx+=p.pos.x; cy+=p.pos.y; cz+=p.pos.z; }
      cx/=particles.length; cy/=particles.length; cz/=particles.length;
      controls.target.set(cx,cy,cz);
      const spread = Math.max(10, Math.sqrt(particles.length) * 3);
      camera.position.set(cx + spread * 0.5, cy + spread * 0.3, cz + spread);
      controls.update();
    }

    // drag handlers
    function getIntersects(clientX, clientY){
      const rect = renderer.domElement.getBoundingClientRect();
      pointer.x = ((clientX - rect.left) / rect.width) * 2 - 1;
      pointer.y = - ((clientY - rect.top) / rect.height) * 2 + 1;
      ray.setFromCamera(pointer, camera);
      return ray.intersectObjects(beadGroup.children, true);
    }

    function onPointerDown(e){
      mouseDown = true;
      const hits = getIntersects(e.clientX, e.clientY);
      if(hits.length>0){
        const hit = hits[0];
        const mesh = hit.object;
        const idx = mesh.userData.index;
        const worldPos = hit.point;
        const p = particles[idx];
        const offset = new THREE.Vector3().subVectors(new THREE.Vector3(p.pos.x,p.pos.y,p.pos.z), worldPos);
        dragging = { index: idx, offset };
        p.vel = { x:0, y:0, z:0 };
      }
    }
    function onPointerMove(e){
      // Hover info
      const hits = getIntersects(e.clientX, e.clientY);
      if (hits.length > 0 && !mouseDown) {
        const mesh = hits[0].object;
        const ud = mesh.userData;
        setHoveredResidue({
          resname: ud.resname,
          resSeq: ud.resSeq,
          chain: ud.chain,
          ss: ud.ss,
          loopIndex: ud.loopIndex
        });
      } else if (!mouseDown) {
        setHoveredResidue(null);
      }

      if(!mouseDown || !dragging) return;
      const hits2 = getIntersects(e.clientX, e.clientY);
      const planePoint = ray.ray.origin.clone().add(ray.ray.direction.clone().multiplyScalar(10));
      const worldPos = hits2.length>0 ? hits2[0].point.clone() : planePoint;
      const newPos = worldPos.add(dragging.offset);
      const p = particles[dragging.index];
      p.pos.x = newPos.x; p.pos.y = newPos.y; p.pos.z = newPos.z;
      p.vel = { x:0, y:0, z:0 };
      syncMeshes();
    }
    function onPointerUp(e){
      mouseDown = false;
      dragging = null;
    }

    renderer.domElement.addEventListener('pointerdown', onPointerDown);
    window.addEventListener('pointermove', onPointerMove);
    window.addEventListener('pointerup', onPointerUp);

    // ---- Protein-bound residue detection ----
    function computeBoundResidues(distanceThreshold) {
      if (particles.length === 0 || ligandAtomsData.length === 0) {
        setBoundResidues([]);
        setBoundResidueInfo([]);
        return;
      }
      
      const bound = new Set();
      const boundInfo = [];
      const dist2 = distanceThreshold * distanceThreshold;
      
      // For each protein residue (particle), check if any ligand atom is within distance threshold
      for (let i = 0; i < particles.length; i++) {
        const p = particles[i];
        let isBound = false;
        
        for (const ligAtom of ligandAtomsData) {
          const dx = p.pos.x - ligAtom.x;
          const dy = p.pos.y - ligAtom.y;
          const dz = p.pos.z - ligAtom.z;
          const d2 = dx*dx + dy*dy + dz*dz;
          
          if (d2 <= dist2) {
            isBound = true;
            break;
          }
        }
        
        if (isBound) {
          bound.add(i);
          const coord = coordsData[i] || {};
          boundInfo.push({
            index: i,
            resname: coord.resname || 'UNK',
            resSeq: coord.resSeq || i + 1,
            chain: coord.chain || 'A'
          });
        }
      }
      
      setBoundResidues(Array.from(bound));
      setBoundResidueInfo(boundInfo);
    }

    // expose controls
    container.buildFromCoords = buildFromCoords;
    container.buildLigand = buildLigand;
    container.generateRandomChain = generateRandomChain;
    container.clearSystem = clearSystem;
    container.toggleLigand = (visible) => { ligandGroup.visible = visible; };
    container.exportPyMOL = exportPyMOL;
    container.computeBoundResidues = computeBoundResidues;

    // ---- Structure view modes: 'both' | 'protein' | 'ligand' | 'split' ----
    container.setViewMode = (mode) => {
      // Reset all group offsets first
      [beadGroup, bondGroup, nbGroup, traceGroup].forEach(g => g.position.set(0,0,0));
      ligandGroup.position.set(0,0,0);

      const proteinGroups = [beadGroup, bondGroup, nbGroup, traceGroup];

      if (mode === 'protein') {
        proteinGroups.forEach(g => { g.visible = true; });
        ligandGroup.visible = false;
        centerView();
        return;
      }

      if (mode === 'ligand') {
        proteinGroups.forEach(g => { g.visible = false; });
        ligandGroup.visible = true;
        // Center camera on ligand
        if (ligandAtomsData.length > 0) {
          let lx = 0, ly = 0, lz = 0;
          ligandAtomsData.forEach(a => { lx += a.x; ly += a.y; lz += a.z; });
          lx /= ligandAtomsData.length; ly /= ligandAtomsData.length; lz /= ligandAtomsData.length;
          let lR = 0;
          ligandAtomsData.forEach(a => {
            const d = Math.sqrt((a.x-lx)**2 + (a.y-ly)**2 + (a.z-lz)**2);
            if (d > lR) lR = d;
          });
          controls.target.set(lx, ly, lz);
          camera.position.set(lx, ly + lR * 0.5, lz + Math.max(lR * 3, 10));
          controls.update();
        }
        return;
      }

      if (mode === 'split') {
        proteinGroups.forEach(g => { g.visible = true; });
        ligandGroup.visible = true;
        if (particles.length === 0 || ligandAtomsData.length === 0) return;

        // Protein center
        let pcx = 0, pcy = 0, pcz = 0;
        particles.forEach(p => { pcx += p.pos.x; pcy += p.pos.y; pcz += p.pos.z; });
        pcx /= particles.length; pcy /= particles.length; pcz /= particles.length;
        let pR = 0;
        particles.forEach(p => {
          const d = Math.sqrt((p.pos.x-pcx)**2+(p.pos.y-pcy)**2+(p.pos.z-pcz)**2);
          if (d > pR) pR = d;
        });

        // Ligand center
        let lcx = 0, lcy = 0, lcz = 0;
        ligandAtomsData.forEach(a => { lcx += a.x; lcy += a.y; lcz += a.z; });
        lcx /= ligandAtomsData.length; lcy /= ligandAtomsData.length; lcz /= ligandAtomsData.length;
        let lR = 0;
        ligandAtomsData.forEach(a => {
          const d = Math.sqrt((a.x-lcx)**2+(a.y-lcy)**2+(a.z-lcz)**2);
          if (d > lR) lR = d;
        });

        const gap = 6;
        const halfSpan = (pR + lR + gap) * 0.5;

        // Shift protein to left, ligand to right — centered on world origin
        const pOff = new THREE.Vector3(-pcx - halfSpan, -pcy, -pcz);
        const lOff = new THREE.Vector3(-lcx + halfSpan, -lcy, -lcz);

        proteinGroups.forEach(g => g.position.copy(pOff));
        ligandGroup.position.copy(lOff);

        // Camera looks at origin between them
        controls.target.set(0, 0, 0);
        const camZ = (pR + lR + gap) * 2;
        camera.position.set(0, (pR + lR) * 0.3, camZ);
        controls.update();
        return;
      }

      // Default: 'both' — restore all groups visible, original positions
      proteinGroups.forEach(g => { g.visible = true; });
      ligandGroup.visible = true;
      centerView();
    };
    container.startSim = () => { threeRef.current.isRunning = true; setRunning(true); };
    container.pauseSim = () => { threeRef.current.isRunning = false; setRunning(false); };
    container.stepSim = () => { simStep(); renderer.render(scene, camera); };
    container.resetSim = () => {
      threeRef.current.isRunning = false; setRunning(false);
      stepCount = 0;
      for(let p of particles){ p.vel = {x:0,y:0,z:0}; }
      setStats({ step:0, K:0, U:0, E:0 });
    };
    container.centerView = centerView;
    container.setColorMode = (mode) => {
      currentColorMode = mode;
      createMeshes();
    };
    container.setParams = (pupdate) => {
      Object.assign(params, pupdate);
      setDtVal(params.dt); setTempVal(params.temp); setEpsVal(params.eps); setGammaVal(params.gamma);
    };
    container.updateProteinLighting = (props) => {
      if (props.metalness !== undefined) currentMetalness = props.metalness;
      if (props.roughness !== undefined) currentRoughness = props.roughness;
      if (props.emissiveIntensity !== undefined) currentEmissiveIntensity = props.emissiveIntensity;
      if (props.lightIntensity !== undefined) l1.intensity = props.lightIntensity;
      const groups = [beadGroup, bondGroup, traceGroup];
      for (const group of groups) {
        group.traverse((child) => {
          if (child.isMesh && child.material && child.material.isMeshStandardMaterial) {
            if (props.metalness !== undefined) child.material.metalness = props.metalness;
            if (props.roughness !== undefined) child.material.roughness = props.roughness;
            if (props.emissiveIntensity !== undefined) {
              child.material.emissiveIntensity = props.emissiveIntensity;
              if (props.emissiveIntensity > 0) {
                child.material.emissive.copy(child.material.color);
              } else {
                child.material.emissive.setHex(0x000000);
              }
            }
            child.material.needsUpdate = true;
          }
        });
      }
    };

    // demo chain
    generateRandomChain(30);

    function onWindowResize(){
      camera.aspect = container.clientWidth / container.clientHeight;
      camera.updateProjectionMatrix();
      renderer.setSize(container.clientWidth, container.clientHeight);
    }
    window.addEventListener('resize', onWindowResize);

    return () => {
      cancelAnimationFrame(animId);
      renderer.domElement.removeEventListener('pointerdown', onPointerDown);
      window.removeEventListener('pointermove', onPointerMove);
      window.removeEventListener('pointerup', onPointerUp);
      window.removeEventListener('resize', onWindowResize);
      container.innerHTML = "";
    };

  }, []);

  // UI handlers
  const handleGenerate = () => {
    const n = parseInt(document.getElementById('res-count').value) || 30;
    rawPDBRef.current = null;
    setHasFullAtom(false);
    setViewMode('both');
    mountRef.current.generateRandomChain(n);
  };

  const handleFile = (ev) => {
    const f = ev.target.files && ev.target.files[0];
    if(!f) return;
    const reader = new FileReader();
    reader.onload = (e) => {
      const text = e.target.result;
      rawPDBRef.current = text;
      setHasFullAtom(true);
      setViewMode('both');
      const coords = parsePDBtoCA(text);
      if(coords.length === 0){ alert('No CA atoms found in PDB file'); return; }
      mountRef.current.buildFromCoords(coords);

      // Also parse ligand if present
      const ligandAtoms = parsePDBLigand(text);
      if (ligandAtoms.length > 0) {
        mountRef.current.buildLigand(ligandAtoms);
        // Compute bound residues after ligand is loaded
        setTimeout(() => {
          if (mountRef.current.computeBoundResidues) {
            mountRef.current.computeBoundResidues(boundResiduesDistance);
          }
        }, 100);
      }

      // Generate PDBQT files
      setPdbqtStatus('generating');
      const protQT = generateProteinPDBQT(text);
      setProteinPDBQT(protQT);
      savePDBQTToServer('/save_protein_pdbqt', protQT);

      if (ligandAtoms.length > 0) {
        const ligQT = generateLigandPDBQT(ligandAtoms);
        setLigandPDBQT(ligQT);
        savePDBQTToServer('/save_ligand_pdbqt', ligQT);
      } else {
        setLigandPDBQT(null);
      }
      setPdbqtStatus('ready');
    };
    reader.readAsText(f);
  };

  const handlePresetLoad = async (preset) => {
    setLoadingPDB(true);
    setPdbqtStatus('generating');
    try {
      const resp = await fetch(`https://files.rcsb.org/download/${preset.pdbId}.pdb`);
      if (!resp.ok) throw new Error(`Failed to fetch PDB: ${resp.status}`);
      const text = await resp.text();
      rawPDBRef.current = text;
      setHasFullAtom(true);
      setViewMode('both');

      const coords = parsePDBtoCA(text);
      if (coords.length === 0) {
        alert('No CA atoms found in the PDB file');
        setLoadingPDB(false);
        setPdbqtStatus(null);
        return;
      }
      mountRef.current.buildFromCoords(coords);

      const ligandAtoms = parsePDBLigand(text);
      if (ligandAtoms.length > 0) {
        mountRef.current.buildLigand(ligandAtoms);
        // Compute bound residues after ligand is loaded
        setTimeout(() => {
          if (mountRef.current.computeBoundResidues) {
            mountRef.current.computeBoundResidues(boundResiduesDistance);
          }
        }, 100);
      }
      setSelectedPreset(preset);

      // Generate PDBQT files
      const protQT = generateProteinPDBQT(text);
      setProteinPDBQT(protQT);
      savePDBQTToServer('/save_protein_pdbqt', protQT);

      if (ligandAtoms.length > 0) {
        const ligQT = generateLigandPDBQT(ligandAtoms);
        setLigandPDBQT(ligQT);
        savePDBQTToServer('/save_ligand_pdbqt', ligQT);
      } else {
        setLigandPDBQT(null);
      }
      setPdbqtStatus('ready');
    } catch (err) {
      alert('Error loading PDB: ' + err.message);
      setPdbqtStatus(null);
    }
    setLoadingPDB(false);
  };

  const savePDBQTToServer = (endpoint, content) => {
    fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'text/plain' },
      body: content
    }).catch(() => {}); // fire-and-forget, non-critical
  };

  const calculateVinaScore = async (protPDBQT, ligPDBQT) => {
    try {
      const response = await fetch('/calculate_vina_score', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          proteinPdbqt: protPDBQT,
          ligandPdbqt: ligPDBQT
        })
      });

      const data = await response.json();
      return data;
    } catch (err) {
      console.error('Error calculating Vina score:', err);
      return { ok: false, error: err.message };
    }
  };

  const downloadPDBQT = (content, filename) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const convertPDBtoPDBQT = (pdbContent) => {
    const lines = pdbContent.split('\n');
    const pdbqtLines = [];
    pdbqtLines.push('REMARK  Converted from PDB to PDBQT format');

    for (const line of lines) {
      const recType = line.substring(0, 6).trim();

      if (recType === 'END') continue;

      // Convert ATOM/HETATM records to PDBQT format
      if (recType === 'ATOM' || recType === 'HETATM') {
        const serial = line.substring(6, 11).trim();
        const name = line.substring(12, 16);
        const altLoc = line.substring(16, 17);
        const resname = line.substring(17, 20);
        const chain = line.substring(21, 22) || 'A';
        const resSeq = line.substring(22, 26);
        const iCode = line.substring(26, 27);
        const x = line.substring(30, 38);
        const y = line.substring(38, 46);
        const z = line.substring(46, 54);
        const occupancy = line.substring(54, 60);
        const tempFactor = line.substring(60, 66);
        const element = line.substring(76, 78).trim() || 'C';

        // Extract autodock type from element
        const autodockType = getAutodockType(element, name);
        const charge = '0.000';

        // Format PDBQT line
        const pdbqtLine = `ATOM  ${serial.padStart(5)} ${name.padEnd(4)}${resname}${chain}${resSeq}    ${x}${y}${z}  ${occupancy} ${tempFactor}    ${charge.padStart(6)} ${autodockType}`;
        pdbqtLines.push(pdbqtLine);
      } else if (recType === 'REMARK' || recType === 'HEADER' || recType === 'TITLE') {
        pdbqtLines.push(line);
      }
    }

    pdbqtLines.push('END');
    return pdbqtLines.join('\n');
  };

  const convertPDBQTtoPDB = (pdbqtContent) => {
    const lines = pdbqtContent.split('\n');
    const pdbLines = [];

    for (const line of lines) {
      const recType = line.substring(0, 6).trim();

      // Skip Vina-specific lines and END
      if (['ROOT', 'ENDROOT', 'TORSDOF', 'BRANCH', 'ENDBRANCH'].includes(recType)) continue;
      if (recType === 'END') continue;

      // Convert ATOM/HETATM records
      if (recType === 'ATOM' || recType === 'HETATM') {
        // Keep standard PDB fields, drop PDBQT-specific fields
        const serial = line.substring(6, 11);
        const name = line.substring(12, 16);
        const altLoc = line.substring(16, 17);
        const resname = line.substring(17, 20);
        const chain = line.substring(21, 22);
        const resSeq = line.substring(22, 26);
        const iCode = line.substring(26, 27);
        const x = line.substring(30, 38);
        const y = line.substring(38, 46);
        const z = line.substring(46, 54);
        const occupancy = line.substring(54, 60);
        const tempFactor = line.substring(60, 66);
        const element = line.substring(76, 78).trim();

        // Rebuild as standard PDB
        const pdbLine = `${recType.padEnd(6)}${serial}${name.padEnd(4)}${altLoc}${resname}${chain}${resSeq}${iCode}   ${x}${y}${z}${occupancy}${tempFactor}          ${element}`;
        pdbLines.push(pdbLine);
      } else if (recType === 'REMARK' || recType === 'HEADER' || recType === 'TITLE') {
        pdbLines.push(line);
      }
    }

    pdbLines.push('END');
    return pdbLines.join('\n');
  };

  const handleCalculateVinaScore = async () => {
    if (!proteinPDBQT || !ligandPDBQT) {
      alert('Need both protein and ligand PDBQT data to calculate Vina score');
      return;
    }

    setVinaScoring(true);
    const result = await calculateVinaScore(proteinPDBQT, ligandPDBQT);
    setVinaScoring(false);

    if (result.ok) {
      setVinaScore({
        affinity: result.affinity,
        binding_energy: result.binding_energy,
        rmsd_lb: result.rmsd_lb,
        rmsd_ub: result.rmsd_ub,
        message: result.message,
        timestamp: new Date().toLocaleString()
      });

      // Fetch the Vina result PDBQT file content
      try {
        const response = await fetch(`/auto_ligand.pdbqt?t=${Date.now()}`);
        if (response.ok) {
          const text = await response.text();
          setVinaResultText(text);

          // Update the 3D ligand pose from the docked result.
          try {
            const dockedAtoms = parseDockedLigandFromPDBQT(text);
            if (dockedAtoms && dockedAtoms.length > 0 && mountRef.current && mountRef.current.buildLigand) {
              mountRef.current.buildLigand(dockedAtoms);
              // Recompute bound residues against the new pose when enabled.
              setTimeout(() => {
                if (mountRef.current && mountRef.current.computeBoundResidues) {
                  mountRef.current.computeBoundResidues(boundResiduesDistance);
                }
              }, 100);
            }
          } catch (poseErr) {
            console.warn('Failed to parse/apply docked ligand pose:', poseErr);
          }
        }
      } catch (err) {
        console.error('Error fetching Vina result file:', err);
      }
    } else {
      alert('Error calculating Vina score: ' + (result.error || result.details || 'Unknown error'));
    }
  };

  // Alias button: user-friendly label for running PyRx-style docking and fetching the result pose.
  const handleRunDockingPyRxResult = async () => {
    return handleCalculateVinaScore();
  };

  const handleViewMode = (mode) => {
    setViewMode(mode);
    if (mountRef.current && mountRef.current.setViewMode) {
      mountRef.current.setViewMode(mode);
    }
  };

  const handleColorModeChange = (mode) => {
    setColorMode(mode);
    if (mountRef.current && mountRef.current.setColorMode) {
      mountRef.current.setColorMode(mode);
    }
  };

  const handleToggleLigand = () => {
    const next = !showLigand;
    setShowLigand(next);
    if (mountRef.current && mountRef.current.toggleLigand) {
      mountRef.current.toggleLigand(next);
    }
  };

  const updateParam = (k,v) => {
    if(mountRef.current) mountRef.current.setParams({ [k]: v });
    if(k === 'dt') setDtVal(v);
    if(k === 'temp') setTempVal(v);
    if(k === 'eps') setEpsVal(v);
    if(k === 'gamma') setGammaVal(v);
  };

  const handleLightingChange = (prop, value) => {
    if (prop === 'metalness') setMetalness(value);
    if (prop === 'roughness') setRoughness(value);
    if (prop === 'emissiveIntensity') setEmissiveIntensity(value);
    if (prop === 'lightIntensity') setLightIntensity(value);
    if (mountRef.current && mountRef.current.updateProteinLighting) {
      mountRef.current.updateProteinLighting({ [prop]: value });
    }
  };

  // Update bound residues when distance threshold or visibility changes
  useEffect(() => {
    if (showBoundResidues && mountRef.current && mountRef.current.computeBoundResidues) {
      mountRef.current.computeBoundResidues(boundResiduesDistance);
      // Re-render meshes to apply bound residue coloring
      if (mountRef.current.setColorMode) {
        mountRef.current.setColorMode(colorMode);
      }
    }
  }, [boundResiduesDistance, showBoundResidues, colorMode]);

  return (
    <>
      <div className="viewer" ref={mountRef} style={{minWidth:0}}>
        {hoveredResidue && (
          <div className="residue-tooltip">
            <strong>{hoveredResidue.resname} {hoveredResidue.resSeq}</strong>
            <span>Chain {hoveredResidue.chain}</span>
            <span className={`ss-badge ss-${hoveredResidue.ss}`}>
              {hoveredResidue.ss === 'helix' ? 'Alpha Helix' : hoveredResidue.ss === 'sheet' ? 'Beta Sheet' : `Loop ${hoveredResidue.loopIndex}`}
            </span>
          </div>
        )}
      </div>

      <div className="panel">
        <h1>Protein Structure Viewer</h1>

        {/* Protein & Ligand Chooser */}
        <div className="controls-block chooser-block">
          <label>{selectedPreset
            ? (selectedPreset.hasLigand
              ? `Chosen Protein & Ligand: ${selectedPreset.name}`
              : `Chosen Protein: ${selectedPreset.name}`)
            : 'Choose Protein & Ligand'}</label>
          <div className="preset-list">
            {PROTEIN_PRESETS.map((preset, idx) => (
              <button
                key={idx}
                className={`preset-btn${preset.hasLigand ? ' has-ligand' : ''}`}
                onClick={() => handlePresetLoad(preset)}
                disabled={loadingPDB}
                title={preset.desc}
              >
                <div className="preset-left">
                  <span className="preset-name">{preset.name}</span>
                  {preset.hasLigand && <span className="ligand-badge">LIGAND</span>}
                </div>
                <span className="preset-id">{preset.pdbId}</span>
              </button>
            ))}
          </div>
          {loadingPDB && <div className="loading-indicator">Loading PDB structure...</div>}
        </div>

        {/* Ligand Info Panel */}
        {ligandInfo && (
          <div className="controls-block ligand-panel">
            <div className="ligand-header">
              <label>Ligand Detected</label>
              <button
                className={`ligand-toggle ${showLigand ? '' : 'secondary'}`}
                onClick={handleToggleLigand}
              >
                {showLigand ? 'Visible' : 'Hidden'}
              </button>
            </div>
            <div className="ligand-details">
              <span className="ligand-name">{ligandInfo.name}</span>
              <span className="ligand-atoms">{ligandInfo.atomCount} atoms</span>
            </div>
            <div className="ligand-elements">
              {ligandInfo.elements.map((el, i) => (
                <span key={i} className="element-chip" style={{
                  backgroundColor: `#${(ELEMENT_COLORS[el] || ELEMENT_COLORS.DEFAULT).toString(16).padStart(6, '0')}`,
                  color: ['H', 'S', 'MG', 'CA', 'F'].includes(el) ? '#111' : '#fff'
                }}>{el}</span>
              ))}
            </div>
          </div>
        )}

        {/* Protein-Bound Residue Detection */}
        {ligandInfo && (
          <div className="controls-block">
            <label>Protein-Bound Residues</label>
            <div className="row">
              <label className="small"><input 
                type="checkbox" 
                checked={showBoundResidues}
                onChange={(e) => {
                  setShowBoundResidues(e.target.checked);
                  if (mountRef.current && mountRef.current.computeBoundResidues) {
                    mountRef.current.computeBoundResidues(boundResiduesDistance);
                  }
                  setTimeout(() => {
                    if (mountRef.current && mountRef.current.createMeshes) {
                      // Re-trigger mesh update via color mode change
                      if (mountRef.current.setColorMode) {
                        mountRef.current.setColorMode(colorMode);
                      }
                    }
                  }, 10);
                }}
              /> Show bound residues</label>
            </div>
            
            {showBoundResidues && (
              <>
                <label className="small">Contact Distance (Å)</label>
                <input 
                  type="range" 
                  min="2" 
                  max="8" 
                  step="0.5" 
                  value={boundResiduesDistance}
                  onChange={(e) => {
                    const newDist = parseFloat(e.target.value);
                    setBoundResiduesDistance(newDist);
                    if (mountRef.current && mountRef.current.computeBoundResidues) {
                      mountRef.current.computeBoundResidues(newDist);
                    }
                    setTimeout(() => {
                      if (mountRef.current && mountRef.current.setColorMode) {
                        mountRef.current.setColorMode(colorMode);
                      }
                    }, 10);
                  }}
                />
                <div className="small">distance = {boundResiduesDistance.toFixed(1)} Å</div>
              </>
            )}
            
            {showBoundResidues && boundResidues.length > 0 && (
              <div className="small" style={{marginTop: 8, padding: 8, backgroundColor: 'rgba(255, 215, 0, 0.1)', borderRadius: 4}}>
                <strong style={{color: '#FFD700'}}>Bound residues: {boundResidues.length}</strong>
                <div style={{marginTop: 4, fontSize: '0.85em', maxHeight: 120, overflow: 'auto'}}>
                  {boundResidueInfo.slice(0, 10).map((info, idx) => (
                    <span key={idx} style={{display: 'block', color: '#FFD700'}}>
                      • {info.resname} {info.resSeq} (Chain {info.chain})
                    </span>
                  ))}
                  {boundResidueInfo.length > 10 && <span style={{color: '#FFD700'}}>... and {boundResidueInfo.length - 10} more</span>}
                </div>
              </div>
            )}
            
            {showBoundResidues && boundResidues.length === 0 && (
              <div className="small" style={{marginTop: 8, color: '#888'}}>
                No residues found within {boundResiduesDistance.toFixed(1)} Å of ligand atoms
              </div>
            )}
          </div>
        )}

        {/* Structure View Mode */}
        <div className="controls-block">
          <label>Structure View</label>
          <div className="row" style={{flexWrap:'wrap', gap:4}}>
            <button
              className={viewMode === 'both' ? '' : 'secondary'}
              onClick={() => handleViewMode('both')}
              title="Show protein and ligand together in docked position"
            >Both (Docked)</button>
            <button
              className={viewMode === 'split' ? '' : 'secondary'}
              onClick={() => handleViewMode('split')}
              disabled={!ligandInfo}
              title="Show protein and ligand side by side as separate structures"
            >Split View</button>
            <button
              className={viewMode === 'protein' ? '' : 'secondary'}
              onClick={() => handleViewMode('protein')}
              title="Show protein only"
            >Protein Only</button>
            <button
              className={viewMode === 'ligand' ? '' : 'secondary'}
              onClick={() => handleViewMode('ligand')}
              disabled={!ligandInfo}
              title="Show ligand only, centered"
            >Ligand Only</button>
          </div>
          <div className="small" style={{marginTop:4}}>
            {viewMode === 'split'   && 'Protein (left) and ligand (right) displayed as separate structures'}
            {viewMode === 'protein' && 'Ligand hidden — protein structure only'}
            {viewMode === 'ligand'  && 'Protein hidden — ligand structure only'}
            {viewMode === 'both'    && 'Both structures shown in original docked positions'}
          </div>
        </div>

        <label>Upload PDB File</label>
        <input className="file-input" type="file" accept=".pdb,text/plain" onChange={handleFile} />

        <label className="small">Or generate random chain</label>
        <div className="row">
          <input id="res-count" type="number" defaultValue={30} min={5} max={1000} />
          <button onClick={handleGenerate}>Generate</button>
        </div>

        {/* Color Mode */}
        <div className="controls-block">
          <label>Color Mode</label>
          <div className="row">
            <button
              className={colorMode === 'structure' ? '' : 'secondary'}
              onClick={() => handleColorModeChange('structure')}
            >
              Structure
            </button>
            <button
              className={colorMode === 'charge' ? '' : 'secondary'}
              onClick={() => handleColorModeChange('charge')}
            >
              Charge
            </button>
          </div>
        </div>

        {/* Protein Lighting */}
        <div className="controls-block lighting-block">
          <label>Protein Lighting</label>
          <label className="small">Metalness</label>
          <input type="range" min="0" max="1" step="0.05" value={metalness}
            onChange={(e) => handleLightingChange('metalness', parseFloat(e.target.value))} />
          <div className="small">metalness = {metalness.toFixed(2)}</div>

          <label className="small">Roughness</label>
          <input type="range" min="0" max="1" step="0.05" value={roughness}
            onChange={(e) => handleLightingChange('roughness', parseFloat(e.target.value))} />
          <div className="small">roughness = {roughness.toFixed(2)}</div>

          <label className="small">Emissive Glow</label>
          <input type="range" min="0" max="1" step="0.05" value={emissiveIntensity}
            onChange={(e) => handleLightingChange('emissiveIntensity', parseFloat(e.target.value))} />
          <div className="small">glow = {emissiveIntensity.toFixed(2)}</div>

          <label className="small">Light Intensity</label>
          <input type="range" min="0" max="3" step="0.1" value={lightIntensity}
            onChange={(e) => handleLightingChange('lightIntensity', parseFloat(e.target.value))} />
          <div className="small">light = {lightIntensity.toFixed(1)}</div>
        </div>

        {/* Structure Legend */}
        {structureInfo && colorMode === 'structure' && (
          <div className="controls-block legend-block">
            <label>Structure Map ({structureInfo.totalResidues} residues)</label>
            <div className="structure-summary">
              <span className="summary-tag helix-tag">{structureInfo.helixCount} Helices</span>
              <span className="summary-tag sheet-tag">{structureInfo.sheetCount} Sheets</span>
              <span className="summary-tag loop-tag">{structureInfo.loopCount} Loops</span>
              <span className="summary-tag chain-tag">{structureInfo.chains.length} Chain(s)</span>
            </div>
            <div className="legend-list">
              {structureInfo.segments.map((seg, idx) => (
                <div key={idx} className="legend-item">
                  <span className="legend-swatch" style={{backgroundColor: seg.color}}></span>
                  <span className="legend-label">{seg.label}</span>
                  <span className="legend-range">res {seg.startRes}-{seg.endRes}</span>
                  <span className="legend-count">({seg.count})</span>
                </div>
              ))}
            </div>
          </div>
        )}

        <div className="controls-block">
          <label>Timestep (dt)</label>
          <input type="range" min="0.1" max="4" step="0.1" value={dtVal} onChange={(e)=>updateParam('dt', parseFloat(e.target.value))} />
          <div className="small">dt = {dtVal.toFixed(2)}</div>

          <label>Temperature</label>
          <input type="range" min="0" max="500" step="10" value={tempVal} onChange={(e)=>updateParam('temp', parseFloat(e.target.value))} />
          <div className="small">T = {tempVal}</div>

          <label>epsilon (LJ strength)</label>
          <input type="range" min="0" max="5" step="0.1" value={epsVal} onChange={(e)=>updateParam('eps', parseFloat(e.target.value))} />
          <div className="small">eps = {epsVal}</div>

          <label>gamma (damping)</label>
          <input type="range" min="0" max="2" step="0.05" value={gammaVal} onChange={(e)=>updateParam('gamma', parseFloat(e.target.value))} />
          <div className="small">gamma = {gammaVal.toFixed(2)}</div>

          <div className="row" style={{marginTop:12}}>
            <button onClick={()=>mountRef.current.startSim()} disabled={running}>Start</button>
            <button className="secondary" onClick={()=>mountRef.current.pauseSim()} disabled={!running}>Pause</button>
            <button className="secondary" onClick={()=>mountRef.current.stepSim()}>Step</button>
            <button className="secondary" onClick={()=>mountRef.current.resetSim()}>Reset</button>
          </div>
        </div>

        <div className="controls-block">
          <label>Display</label>
          <div className="row">
            <label className="small"><input id="show-bonds" type="checkbox" defaultChecked/> Bonds</label>
            <label className="small"><input id="show-nonbond" type="checkbox" defaultChecked/> Nonbond</label>
            <label className="small"><input id="show-trace" type="checkbox" defaultChecked/> Trace</label>
          </div>
        </div>

        {/* Export to PyMOL */}
        <div className="controls-block">
          <label>Export</label>
          <button
            className="pymol-export-btn"
            onClick={() => mountRef.current.exportPyMOL()}
          >
            {hasFullAtom ? 'Export Full Structure to PyMOL (.pml)' : 'Export to PyMOL (.pml)'}
          </button>
          <div className="small">
            {hasFullAtom
              ? 'Full-atom protein + ligand — cartoon + binding-site sticks'
              : 'Downloads a PyMOL script with protein backbone + ligand'}
          </div>
        </div>

        {/* PDBQT Files for AutoDock Vina */}
        <div className="controls-block">
          <label>PDBQT Files (AutoDock Vina)</label>
          {pdbqtStatus === 'generating' && (
            <div className="loading-indicator">Generating PDBQT...</div>
          )}
          {pdbqtStatus === 'ready' && proteinPDBQT && (
            <button
              className="pymol-export-btn"
              onClick={() => downloadPDBQT(proteinPDBQT, 'protein.pdbqt')}
            >
              Download Protein PDBQT
            </button>
          )}
          {pdbqtStatus === 'ready' && ligandPDBQT && (
            <button
              className="pymol-export-btn"
              style={{marginTop: 6}}
              onClick={() => downloadPDBQT(ligandPDBQT, 'ligand.pdbqt')}
            >
              Download Ligand PDBQT
            </button>
          )}
          {pdbqtStatus === 'ready' && proteinPDBQT && ligandPDBQT && (
            <button
              className="pymol-export-btn"
              style={{marginTop: 6, backgroundColor: '#4CAF50'}}
              onClick={handleCalculateVinaScore}
              disabled={vinaScoring}
            >
              {vinaScoring ? 'Calculating Vina Score...' : 'Calculate Vina Score'}
            </button>
          )}

          {pdbqtStatus === 'ready' && proteinPDBQT && ligandPDBQT && (
            <button
              className="pymol-export-btn"
              style={{marginTop: 6}}
              onClick={handleRunDockingPyRxResult}
              disabled={vinaScoring}
            >
              {vinaScoring ? 'Running PyRx Docking...' : 'RunDocking PyRx Result'}
            </button>
          )}
          {!pdbqtStatus && (
            <div className="small">Load a protein preset or PDB file to generate PDBQT files</div>
          )}
          {pdbqtStatus === 'ready' && !ligandPDBQT && (
            <div className="small">No ligand detected — only protein PDBQT available</div>
          )}

          {/* Vina Score Display */}
          {vinaScore && (
            <div className="small" style={{marginTop: 12, padding: 10, backgroundColor: 'rgba(76, 175, 80, 0.15)', borderRadius: 4}}>
              <strong style={{color: '#4CAF50'}}>Vina Docking Results</strong>
              <div style={{marginTop: 6, fontSize: '0.95em', lineHeight: '1.6'}}>
                <div style={{color: '#2E7D32', fontWeight: 'bold'}}>
                  Binding Energy: {vinaScore.affinity.toFixed(2)} kcal/mol
                </div>
                <div style={{color: '#555', marginTop: 4}}>
                  Lower bound RMSD: {vinaScore.rmsd_lb.toFixed(3)} Å
                </div>
                <div style={{color: '#555'}}>
                  Upper bound RMSD: {vinaScore.rmsd_ub.toFixed(3)} Å
                </div>
                <div style={{color: '#888', fontSize: '0.85em', marginTop: 4}}>
                  {vinaScore.message} • {vinaScore.timestamp}
                </div>
              </div>
              <button
                className="pymol-export-btn"
                style={{marginTop: 8, width: '100%'}}
                onClick={() => {
                  const a = document.createElement('a');
                  a.href = '/auto_ligand.pdbqt';
                  a.download = 'auto_ligand.pdbqt';
                  document.body.appendChild(a);
                  a.click();
                  document.body.removeChild(a);
                }}
              >
                Download Vina Result (PDBQT)
              </button>

              {/* Vina Result Text Display */}
              {vinaResultText && (
                <div style={{marginTop: 10, maxHeight: 600, overflow: 'auto', backgroundColor: '#f5f5f5', padding: 12, borderRadius: 4, border: '2px solid #4CAF50'}}>
                  <strong style={{color: '#333', fontSize: '0.95em', display: 'block', marginBottom: 8}}>PDBQT Result (Full Structure):</strong>
                  <pre style={{margin: 0, fontSize: '0.8em', color: '#1a1a1a', whiteSpace: 'pre-wrap', wordWrap: 'break-word', fontFamily: '"Courier New", monospace', lineHeight: '1.4'}}>
                    {vinaResultText}
                  </pre>
                </div>
              )}
            </div>
          )}
        </div>

        <div className="controls-block">
          <h3 style={{margin:'8px 0 4px 0'}}>Simulation stats</h3>
          <div className="stat">Step: {stats.step}</div>
          <div className="stat">Kinetic (K): {stats.K.toFixed(3)}</div>
          <div className="stat">Potential (U): {stats.U.toFixed(3)}</div>
          <div className="stat">Total E: {stats.E.toFixed(3)}</div>
        </div>

        <footer>
          <div className="small">Drag atoms to reposition. Hover for residue info. Each loop/helix/sheet has a unique color.</div>
        </footer>
      </div>
    </>
  );
}
